# Generated by Django 4.0.4 on 2022-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='city_code',
            field=models.CharField(max_length=252, null=True),
        ),
    ]
